server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            routes:
                - id: gerenciamento
                  uri: lb://gerenciamento/produto/
                  predicates:
                      - Path=/gerenciamento/produto/**
                - id: gerenciamento
                  uri: lb://gerenciamento/cardapio/
                  predicates:
                      - Path=/gerenciamento/cardapio/**

                # - id: atendimento
                #   uri: lb://atendimento/mesas/
                #   predicates:
                #       - Path=/atendimento/mesas/**

                # - id: atendimento
                #   uri: lb://atendimento/contas/
                #   predicates:
                #       - Path=/atendimento/contas/**

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost
