server:
    port: 8080

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

spring:
    application:
        name: "atendimento"
    data:
        mongodb:
            authentication-database: admin
            username: rootuser
            password: rootpass
            database: atendimento
            port: 27017
            host: localhost
            auto-index-creation: true

    mvc:
        pathmatch:
            matching-strategy: ant-path-matcher

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka
